# Generated by Django 2.2.12 on 2020-07-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='логин пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='пароль пользователя')),
                ('e_mail', models.EmailField(max_length=50, verbose_name='пароль пользователя')),
            ],
        ),
    ]
